server:
  port: 8081
spring:
  cloud: 
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/Eri-random/Arquitectura-De-Microservicios
          search-paths: config-data
  application:
    name: config-services